FROM docker.io/library/golang:1.24-alpine AS build

WORKDIR /app
COPY go.mod ./
COPY . .
ENV GOPROXY=https://goproxy.cn,direct
RUN go build -o main ./cmd/server

FROM alpine:latest
WORKDIR /root/
COPY --from=build /app/main .

EXPOSE 8080
CMD ["./main"]